### ISSUE TITLE
Correct Changelog

### ISSUE THREAD

**Issue by slayerplayer99** [apophis775/NewEdenColonialMarines#54]
![changelog](https://cloud.githubusercontent.com/assets/9739279/6567460/fc7ae3e6-c684-11e4-9ee4-37184ebb145c.jpg)

replace me with Secretstamos

**Comment by rahlzel** [comment]
Why not do it yourself and PR it?

**Comment by slayerplayer99** [comment]
Cause I thought apop was going to handle the changelog

**Comment by rahlzel** [comment]
Apophis has enough on his plate. He's too nice.

This is something every SS13 dev needs to learn: http://newedenstation.com/showthread.php?tid=1354

**Comment by slayerplayer99** [comment]
I already know how to work it, it's just if I do PR it someone usually has one in their commit so it conflicts when PRs start to merge

**Comment by rahlzel** [comment]
"Usually", meaning that one time?

I have Collaborator access here now, so I can merge your change in immediately. That'll help alleviate merge conflicts.
